=== hlim1/cbiexp/src/view.dtd
<!ELEMENT view (schemes, sorts, predictors)>
<!ATTLIST view prefix NMTOKEN #REQUIRED>
<!ATTLIST view summary NMTOKEN #REQUIRED>

<!ELEMENT schemes (scheme+)>
<!ATTLIST schemes current IDREF #REQUIRED>

<!ELEMENT scheme EMPTY>
<!ATTLIST scheme code ID #REQUIRED>
<!ATTLIST scheme name CDATA #REQUIRED>

<!ELEMENT sorts EMPTY>
<!ATTLIST sorts current (lb|is|fs|nf) #REQUIRED>

<!ELEMENT predictors (predictor+)>
<!ELEMENT predictor (true, seen, scores, source)>

<!ELEMENT true EMPTY>
<!ELEMENT seen EMPTY>
<!ENTITY % tally "success NMTOKEN #REQUIRED failure NMTOKEN #REQUIRED">
<!ATTLIST true %tally;>
<!ATTLIST seen %tally;>

<!ELEMENT scores EMPTY>
<!ATTLIST scores
  log10-seen NMTOKEN #REQUIRED
  badness NMTOKEN #REQUIRED
  context NMTOKEN #REQUIRED
  increase NMTOKEN #REQUIRED
  lower-bound NMTOKEN #REQUIRED>

<!ELEMENT source EMPTY>
<!ATTLIST source
  predicate CDATA #REQUIRED
  function NMTOKEN #REQUIRED
  file CDATA #REQUIRED
  line NMTOKEN #REQUIRED>

=== hlim1/cbiexp/pldi-2004/moss-view/all_lbnf_none.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="moss-view.xsl"?><!DOCTYPE view SYSTEM "view.dtd"><view scheme="all" sort="lbnf" projection="none"><predictor index="2629"/><predictor index="2734"/><predictor index="2729"/><predictor index="2630"/><predictor index="2698"/><predictor index="2728"/><predictor index="1239"/><predictor index="1148"/><predictor index="1145"/><predictor index="1286"/><predictor index="1374"/><predictor index="1150"/><predictor index="1221"/><predictor index="1324"/><predictor index="1146"/><predictor index="1147"/><predictor index="1373"/><predictor index="1285"/><predictor index="1372"/><predictor index="1149"/><predictor index="111"/><predictor index="2482"/><predictor index="2501"/><predictor index="2540"/><predictor index="2570"/><predictor index="2602"/><predictor index="2690"/><predictor index="1152"/><predictor index="2586"/><predictor index="1138"/><predictor index="1136"/><predictor index="1154"/><predictor index="2599"/><predictor index="2600"/><predictor index="2601"/><predictor index="2603"/><predictor index="2717"/><predictor index="2718"/><predictor index="1153"/><predictor index="2595"/><predictor index="2596"/><predictor index="2597"/><predictor index="2598"/><predictor index="2483"/><predictor index="2498"/><predictor index="2502"/><predictor index="2541"/><predictor index="2571"/><predictor index="1156"/><predictor index="1157"/><predictor index="951"/><predictor index="949"/><predictor index="1160"/><predictor index="950"/><predictor index="1155"/><predictor index="1159"/><predictor index="1137"/><predictor index="1238"/><predictor index="1126"/><predictor index="954"/><predictor index="953"/><predictor index="1158"/><predictor index="1127"/><predictor index="1323"/><predictor index="534"/><predictor index="943"/><predictor index="956"/><predictor index="1533"/><predictor index="1527"/><predictor index="1532"/><predictor index="1645"/><predictor index="1162"/><predictor index="1638"/><predictor index="1643"/><predictor index="1597"/><predictor index="1485"/><predictor index="1648"/><predictor index="1633"/><predictor index="1535"/><predictor index="1647"/><predictor index="945"/><predictor index="1132"/><predictor index="1537"/><predictor index="1632"/><predictor index="1612"/><predictor index="1622"/><predictor index="1517"/><predictor index="1630"/><predictor index="1511"/><predictor index="1628"/><predictor index="1499"/><predictor index="1053"/><predictor index="1611"/><predictor index="1500"/><predictor index="1519"/><predictor index="1521"/><predictor index="1056"/><predictor index="2691"/><predictor index="1623"/><predictor index="1496"/><predictor index="998"/><predictor index="1608"/><predictor index="958"/><predictor index="1512"/><predictor index="831"/><predictor index="959"/><predictor index="1540"/><predictor index="1539"/><predictor index="1497"/><predictor index="1609"/><predictor index="1055"/><predictor index="173"/><predictor index="403"/><predictor index="1542"/><predictor index="1652"/><predictor index="1059"/><predictor index="1115"/><predictor index="1035"/><predictor index="1651"/><predictor index="1164"/><predictor index="1545"/><predictor index="1052"/><predictor index="130"/><predictor index="2557"/><predictor index="2558"/><predictor index="2564"/><predictor index="331"/><predictor index="1057"/><predictor index="1654"/><predictor index="934"/><predictor index="1655"/><predictor index="1544"/><predictor index="1403"/><predictor index="1244"/><predictor index="378"/><predictor index="1360"/><predictor index="1259"/><predictor index="1332"/><predictor index="1397"/><predictor index="1405"/><predictor index="1386"/><predictor index="1547"/><predictor index="375"/><predictor index="1406"/><predictor index="1117"/><predictor index="1329"/><predictor index="1396"/><predictor index="1128"/><predictor index="1402"/><predictor index="1379"/><predictor index="1231"/><predictor index="1658"/><predictor index="1388"/><predictor index="1395"/><predictor index="1657"/><predictor index="1368"/><predictor index="1054"/><predictor index="1404"/><predictor index="1390"/><predictor index="1401"/><predictor index="1378"/><predictor index="1382"/><predictor index="1394"/><predictor index="1387"/><predictor index="1385"/><predictor index="1383"/><predictor index="1392"/><predictor index="1222"/><predictor index="1393"/><predictor index="1408"/><predictor index="1407"/><predictor index="1400"/><predictor index="1227"/><predictor index="434"/><predictor index="938"/><predictor index="1409"/><predictor index="1548"/><predictor index="1398"/><predictor index="1384"/><predictor index="1660"/><predictor index="830"/><predictor index="1229"/><predictor index="935"/><predictor index="1550"/><predictor index="1661"/><predictor index="1551"/><predictor index="1554"/><predictor index="1375"/><predictor index="1664"/><predictor index="1663"/><predictor index="1163"/><predictor index="1553"/><predictor index="1167"/><predictor index="2585"/><predictor index="889"/><predictor index="1287"/><predictor index="1304"/><predictor index="1296"/><predictor index="1501"/><predictor index="1161"/><predictor index="25"/><predictor index="827"/><predictor index="1613"/><predictor index="1503"/><predictor index="23"/><predictor index="926"/><predictor index="1615"/><predictor index="1666"/><predictor index="1295"/><predictor index="961"/><predictor index="24"/><predictor index="1169"/><predictor index="825"/><predictor index="1166"/><predictor index="2730"/><predictor index="1130"/><predictor index="2692"/><predictor index="2731"/><predictor index="2694"/><predictor index="2733"/><predictor index="2627"/><predictor index="2732"/><predictor index="2726"/><predictor index="2488"/><predictor index="2507"/><predictor index="2546"/><predictor index="2576"/><predictor index="2608"/><predictor index="892"/><predictor index="2486"/><predictor index="2505"/><predictor index="2544"/><predictor index="2574"/><predictor index="2606"/><predictor index="1290"/><predictor index="928"/><predictor index="1170"/><predictor index="1171"/><predictor index="2655"/><predictor index="1292"/><predictor index="952"/><predictor index="1116"/><predictor index="963"/><predictor index="1558"/><predictor index="2672"/><predictor index="1045"/><predictor index="1097"/><predictor index="1557"/><predictor index="1668"/><predictor index="1507"/><predictor index="1505"/><predictor index="1165"/><predictor index="1289"/><predictor index="2609"/><predictor index="1560"/><predictor index="2554"/><predictor index="2555"/><predictor index="2562"/><predictor index="2563"/><predictor index="510"/><predictor index="1669"/><predictor index="1060"/><predictor index="1168"/><predictor index="1220"/><predictor index="1313"/><predictor index="2489"/><predictor index="2508"/><predictor index="2547"/><predictor index="2577"/><predictor index="1522"/><predictor index="1671"/><predictor index="1133"/><predictor index="965"/><predictor index="915"/><predictor index="867"/><predictor index="1305"/><predictor index="868"/><predictor index="1067"/><predictor index="533"/><predictor index="1675"/><predictor index="916"/><predictor index="1301"/><predictor index="1063"/><predictor index="1563"/><predictor index="139"/><predictor index="786"/><predictor index="138"/><predictor index="936"/><predictor index="787"/><predictor index="509"/><predictor index="1617"/><predictor index="1173"/><predictor index="1565"/><predictor index="1674"/><predictor index="948"/><predictor index="755"/><predictor index="937"/><predictor index="2591"/><predictor index="1677"/><predictor index="1047"/><predictor index="1280"/><predictor index="141"/><predictor index="1233"/><predictor index="144"/><predictor index="1106"/><predictor index="1062"/><predictor index="544"/><predictor index="1568"/><predictor index="1508"/><predictor index="1061"/><predictor index="1322"/><predictor index="1151"/><predictor index="1038"/><predictor index="1680"/><predictor index="1314"/><predictor index="2484"/><predictor index="2503"/><predictor index="2542"/><predictor index="2572"/><predictor index="2604"/><predictor index="1036"/><predictor index="1371"/><predictor index="1237"/><predictor index="1309"/><predictor index="1320"/><predictor index="1120"/><predictor index="1310"/><predictor index="1311"/><predictor index="1108"/><predictor index="1312"/><predictor index="1619"/><predictor index="1042"/><predictor index="1122"/><predictor index="1303"/><predictor index="1370"/><predictor index="1172"/><predictor index="131"/><predictor index="1064"/><predictor index="1040"/><predictor index="1306"/><predictor index="1631"/><predictor index="1487"/><predictor index="1520"/><predictor index="1572"/><predictor index="132"/><predictor index="140"/><predictor index="1599"/><predictor index="1307"/><predictor index="1302"/><predictor index="1308"/><predictor index="1046"/><predictor index="829"/><predictor index="2701"/><predictor index="2639"/><predictor index="2605"/><predictor index="905"/><predictor index="1489"/><predictor index="1686"/><predictor index="1298"/><predictor index="1129"/><predictor index="849"/><predictor index="135"/><predictor index="841"/><predictor index="1601"/><predictor index="490"/><predictor index="2637"/><predictor index="338"/><predictor index="1232"/><predictor index="929"/><predictor index="844"/><predictor index="1574"/><predictor index="893"/><predictor index="890"/><predictor index="822"/><predictor index="855"/><predictor index="856"/><predictor index="861"/><predictor index="1135"/><predictor index="939"/><predictor index="850"/><predictor index="2660"/><predictor index="1687"/><predictor index="495"/><predictor index="549"/><predictor index="1175"/><predictor index="1300"/><predictor index="1066"/><predictor index="852"/><predictor index="2679"/><predictor index="819"/><predictor index="1576"/><predictor index="336"/><predictor index="984"/><predictor index="2646"/><predictor index="1594"/><predictor index="1210"/><predictor index="1206"/><p
